# Generated by Django 4.2.7 on 2023-11-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
